name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04', 'macos-13', 'windows-2022']
        build-system: ['autotools', 'meson']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout audacious
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Configure
      uses: ./.github/actions/run-action
      with:
        action: 'configure'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Build
      uses: ./.github/actions/run-action
      with:
        action: 'build'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Test
      if: startsWith(matrix.os, 'ubuntu')
      uses: ./.github/actions/run-action
      with:
        action: 'test'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}
